/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import Connection.MyConnection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import entites.Rubrique;
import gui.Rubriques;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.*;
import java.awt.*;
import DAO.AdminDAO;

/**
 *
 * @author manel101
 */
public class AuthentificationAdmin extends javax.swing.JFrame {

  
    
    /**
     * Creates new form Rubrique
     */
      public AuthentificationAdmin() {
          
   
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TLogin = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonOK = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setText("Login :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 70, 90, 30);

        jLabel2.setText("Password");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 120, 90, 30);

        TLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TLoginActionPerformed(evt);
            }
        });
        jPanel2.add(TLogin);
        TLogin.setBounds(200, 70, 140, 30);
        jPanel2.add(jPassword);
        jPassword.setBounds(200, 120, 140, 30);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonOK);
        jButtonOK.setBounds(297, 203, 80, 30);

        jButtonAnnuler.setText("Annuler");
        jPanel2.add(jButtonAnnuler);
        jButtonAnnuler.setBounds(199, 203, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TLoginActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
boolean exist=false;
        AdminDAO A= new AdminDAO();
      exist =  A.Authentifier(TLogin.getText().toString(), jPassword.getText().toString());
           if (!exist) {
                System.out.println("non vlide");
                JOptionPane a = new JOptionPane();
                a.showMessageDialog(null, "nom et mot de pass non valide");

            } else {
                System.out.println("valide");
                JOptionPane.showMessageDialog(null, "nom et mot de pass valide");
                dispose();
                Rubriques n = new Rubriques();
                n.setVisible(true);

            }

        
        
           /* try {

            
            //System.out.println("login :" + TNomAdmin.getText());
            //System.out.println("pass :" + TPass.getText());
            PreparedStatement pst = MyConnection.getInstance().prepareStatement("select Login,password from Admin where login='" +TLogin.getText() + "'and password='" + jPassword.getText() + "'");

            rs = pst.executeQuery();
            boolean exist = false;
            while (rs.next()) {
                exist = true;
                System.out.println("exist");
            }
            if (!exist) {
                System.out.println("dans non vlide");
                JOptionPane a = new JOptionPane();
                a.showMessageDialog(null, "nom et mot de pass non valide");

            } else {
                System.out.println("valide");
                JOptionPane.showMessageDialog(null, "nom et mot de pass valide");
                dispose();
                Rubriques n = new Rubriques();
                n.setVisible(true);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }      */
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthentificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthentificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthentificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthentificationAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthentificationAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TLogin;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    // End of variables declaration//GEN-END:variables
}
